### ISSUE TITLE
Add back ante handler after signature verification issue is resolved

### ISSUE THREAD

**Issue by shanev** [TruStory/truchain#364]
There currently are issues with signature verification. Some characters seem to fail. Most likely some sort of encoding issue.

Until this is resolved, I commented out the ante handler, which is responsible for verifying signatures and collecting fees.

See https://github.com/TruStory/TruStory-mobile/issues/296.

**Comment by jhernandezb** [comment]
fixed in https://github.com/TruStory/truchain/pull/839
